[tool.poetry]
name = "jspsych"
version = "7.2.2"
description = "A JavaScript library for creating behavioral experiments in a web browser"
authors = ["Josh de Leeuw <josh.deleeuw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
